In [5]:
import pandas as pd

df = pd.read_csv("Employees.csv")
print(df)

   EmpID    Name Department Joining Date  Salary    Bonus
0    101   Viraj         IT     15-02-21    80000  2000.0
1    102  Rakesh         HR     23-07-19    75000  3000.0
2    103  Yogesh    Finance     01-12-20    90000  2500.0
3    104    Ajay         HR     05-01-22    78000  1500.0
4    105  Vikram    Finance     15-09-21    91000  1000.0
5    106   Vinay         HR     18-05-20    82000     NaN

In [6]:
df.head()

   EmpID    Name Department Joining Date  Salary    Bonus
0    101   Viraj         IT     15-02-21    80000  2000.0
1    102  Rakesh         HR     23-07-19    75000  3000.0
2    103  Yogesh    Finance     01-12-20    90000  2500.0
3    104    Ajay         HR     05-01-22    78000  1500.0
4    105  Vikram    Finance     15-09-21    91000  1000.0

In [7]:
df.describe()

            EmpID       Salary         Bonus
count    6.000000      6.000000     5.000000
mean   103.500000  82666.666667  2000.000000
std      1.870829   6501.281925   790.569415
min    101.000000  75000.000000  1000.000000
25%    102.250000  78500.000000  1500.000000
50%    103.500000  81000.000000  2000.000000
75%    104.750000  88000.000000  2500.000000
max    106.000000  91000.000000  3000.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EmpID         6 non-null      int64
 1   Name          6 non-null      object
 2   Department    6 non-null      object
 3   Joining Date  6 non-null      object
 4   Salary        6 non-null      int64
 5   Bonus         5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 416.0+ bytes

In [10]:
# Data Cleaning
#fill missing bonus with 0
df['Bonus'] = df['Bonus'].fillna(0)

#filling missing salary with median

#df['Salary'] = df['Salary'].fillna(df['Salary'].median())

#convert to datetime
df['Joining Date'] = pd.to_datetime(df['Joining Date'])

#drop duplicates
df = df.drop_duplicates()

In [11]:
print(df)

   EmpID    Name Department Joining Date  Salary    Bonus
0    101   Viraj         IT   2021-02-15    80000  2000.0
1    102  Rakesh         HR   2019-07-23    75000  3000.0
2    103  Yogesh    Finance   2020-01-12    90000  2500.0
3    104    Ajay         HR   2022-05-01    78000  1500.0
4    105  Vikram    Finance   2021-09-15    91000  1000.0
5    106   Vinay         HR   2020-05-18    82000     0.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EmpID         6 non-null      int64
 1   Name          6 non-null      object
 2   Department    6 non-null      object
 3   Joining Date  6 non-null      datetime64[ns]
 4   Salary        6 non-null      int64
 5   Bonus         6 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 336.0+ bytes

In [30]:
# Transformation
# adding compensation column [ salary + bonus]
# Extract joining date

#df['total compensation'] = df['Salary'] + df['Bonus']
df['Joining year'] = df['Joining Date'].dt.year

df.head()

   EmpID    Name Department Joining Date  Salary    Bonus  Joining year
0    101   Viraj         IT   2021-02-15    80000  2000.0          2021
1    102  Rakesh         HR   2019-07-23    75000  3000.0          2019
2    103  Yogesh    Finance   2020-01-12    90000  2500.0          2020
3    104    Ajay         HR   2022-05-01    78000  1500.0          2022
4    105  Vikram    Finance   2021-09-15    91000  1000.0          2021

In [27]:
print(df.columns.tolist())

['EmpID', 'Name', 'Department', 'Joining Date', 'Salary ', 'Bonus']

In [36]:
#analysis
#Average salary by department.
#Find top 3 highest-paid employees.
#Count employees joined per year.

#avg salary by department
print(df.groupby('Department')['Salary'].mean())

KeyError: 'Column not found: Salary'

In [39]:
df['Bonus']

0    2000.0
1    3000.0
2    2500.0
3    1500.0
4    1000.0
5       0.0
Name: Bonus, dtype: float64

In [41]:
df['Salary']

KeyError: 'Salary'

In [46]:
df['Salary']

KeyError: 'Salary'

In [50]:
df

KeyError: 'Salary'

In [51]:
print(df.columns.tolist())

['EmpID', 'Name', 'Department', 'Joining Date', 'Salary ', 'Bonus', 'Joining year']

In [52]:
df['Salary ']

0    80000
1    75000
2    90000
3    78000
4    91000
5    82000
Name: Salary , dtype: int64

In [54]:

#avg salary by department
print(df.groupby('Department')['Salary '].mean())

Department
Finance    90500.000000
HR         78333.333333
IT         80000.000000
Name: Salary , dtype: float64

In [55]:
# Transformation
# adding compensation column [ salary + bonus]
# Extract joining date

df['total compensation'] = df['Salary '] + df['Bonus']
df['Joining year'] = df['Joining Date'].dt.year

In [56]:
df

,EmpID,Name,Department,Joining Date,Salary,Bonus,Joining year,total compensation
0,101,Viraj,IT,2021-02-15,80000,2000.0,2021,82000.0
1,102,Rakesh,HR,2019-07-23,75000,3000.0,2019,78000.0
2,103,Yogesh,Finance,2020-01-12,90000,2500.0,2020,92500.0
3,104,Ajay,HR,2022-05-01,78000,1500.0,2022,79500.0
4,105,Vikram,Finance,2021-09-15,91000,1000.0,2021,92000.0
5,106,Vinay,HR,2020-05-18,82000,0.0,2020,82000.0

In [59]:
# Avg salary by department
print(df.groupby("Department")['Salary '].mean())

# Top 3 highest paid
#print(df.nlargest(3, 'Total Compensation'))

print(df.nlargest(3,'total compensation'))

# Count employees joined each year
#print(df['Joining Year'].value_counts())

print(df['Joining year'].value_counts())

Department
Finance    90500.000000
HR         78333.333333
IT         80000.000000
Name: Salary , dtype: float64
   EmpID    Name Department Joining Date  Salary    Bonus  Joining year  \
2    103  Yogesh    Finance   2020-01-12    90000  2500.0          2020
4    105  Vikram    Finance   2021-09-15    91000  1000.0          2021
0    101   Viraj         IT   2021-02-15    80000  2000.0          2021

   total compensation
2             92500.0
4             92000.0
0             82000.0
2021    2
2020    2
2022    1
2019    1
Name: Joining year, dtype: int64

In [60]:
# saving clean dataset
df.to_csv("cleaned_employee.csv",index = False)
print(df)

   EmpID    Name Department Joining Date  Salary    Bonus  Joining year  \
0    101   Viraj         IT   2021-02-15    80000  2000.0          2021
1    102  Rakesh         HR   2019-07-23    75000  3000.0          2019
2    103  Yogesh    Finance   2020-01-12    90000  2500.0          2020
3    104    Ajay         HR   2022-05-01    78000  1500.0          2022
4    105  Vikram    Finance   2021-09-15    91000  1000.0          2021
5    106   Vinay         HR   2020-05-18    82000     0.0          2020

   total compensation
0             82000.0
1             78000.0
2             92500.0
3             79500.0
4             92000.0
5             82000.0

In [62]:
# employee who joined the company earliest
earliest_emp = df.loc[df["Joining Date"].idxmin()]
print("Earliest joined employee")
print(earliest_emp)

Earliest joined employee
EmpID                                 102
Name                               Rakesh
Department                             HR
Joining Date          2019-07-23 00:00:00
Salary                              75000
Bonus                                3000
Joining year                         2019
total compensation                  78000
Name: 1, dtype: object

In [68]:
#finding employees earning above dept avg salary
dept_avg_sal = df.groupby("Department")["Salary "].transform("mean")
print(dept_avg_sal)

#filtering employees
above_avg_emp = df[df["Salary "] > dept_avg_sal]
print(above_avg_emp)

0    80000.000000
1    78333.333333
2    90500.000000
3    78333.333333
4    90500.000000
5    78333.333333
Name: Salary , dtype: float64
   EmpID    Name Department Joining Date  Salary    Bonus  Joining year  \
4    105  Vikram    Finance   2021-09-15    91000  1000.0          2021
5    106   Vinay         HR   2020-05-18    82000     0.0          2020

   total compensation
4             92000.0
5             82000.0

In [67]:
df

,EmpID,Name,Department,Joining Date,Salary,Bonus,Joining year,total compensation
0,101,Viraj,IT,2021-02-15,80000,2000.0,2021,82000.0
1,102,Rakesh,HR,2019-07-23,75000,3000.0,2019,78000.0
2,103,Yogesh,Finance,2020-01-12,90000,2500.0,2020,92500.0
3,104,Ajay,HR,2022-05-01,78000,1500.0,2022,79500.0
4,105,Vikram,Finance,2021-09-15,91000,1000.0,2021,92000.0
5,106,Vinay,HR,2020-05-18,82000,0.0,2020,82000.0

In [70]:
# creating summary of dataframe with dept wise - min,max,avg-salary
#dept_summary = df.groupby("department")["salary"].agg(
   # min_salary="min",
  #  max_salary="max",
 #   avg_salary="mean"
#).reset_index()

#print("Department-wise Salary Summary:")
#print(dept_summary)

dept_summary = df.groupby("Department")["Salary "].agg(
    min_salary = "min",
    max_salary = 'max',
    avg_salary = "mean"
).reset_index()

print("Department-wise Salary Summary")
print(dept_summary)

Department-wise Salary Summary
  Department  min_salary  max_salary    avg_salary
0    Finance       90000       91000  90500.000000
1         HR       75000       82000  78333.333333
2         IT       80000       80000  80000.000000

In [72]:
# finding the department highest avg bonus.
#dept_avg_bonus = df.groupby("department")["bonus"].mean().reset_index()
#dept_highest_bonus = dept_avg_bonus.loc[dept_avg_bonus["bonus"].idxmax()]

#print("Department with highest average bonus:")
#print(dept_highest_bonus)

dept_avg_bonus = df.groupby("Department")["Bonus"].mean().reset_index()

dept_highest_bonus = dept_avg_bonus.loc[dept_avg_bonus["Bonus"].idxmax()]

print("Department with highest average bonus:")
print(dept_highest_bonus)

Department with highest average bonus:
Department      IT
Bonus         2000
Name: 2, dtype: object